### ISSUE TITLE
Troubles with import 1.2.0

### ISSUE THREAD

**Issue by yankauskas** [kotomisak/security-showcase-android#27]
Got a problem with my build.gradle

   // KeystoreCompat
    implementation('cz.koto:android-keystore-compat:1.2.0') {
        exclude group: 'com.android.support'
    }

"Failed to resolve: android-keystore-compat"

Maybe you've forgotten to add .aar file to bintray?

https://bintray.com/kotomisak/cz.koto/android-keystore-compat/1.2.0#files/cz/koto/android-keystore-compat

**Comment by kotomisak** [comment]
Thx! Viktor.

It was a problem with unwanted flavours (accidentally taken from example app).
It should be fixed now.

I have been working on the version where you can choose the min-api variant.
It means if your min api is 21, then you don’t want to bundle code for API19 support. etc.

Then I will already publish also the sample app to playstore.

Have a great day!

**Comment by yankauskas** [comment]
Hi! 

Fixed. Thanks for publishing a new version. It's extremely useful.

Goog luck
