### ISSUE TITLE
Deceptive device settings changes policy

### ISSUE THREAD

**Issue by mradzinski** [kotomisak/security-showcase-android#28]
Hi, quick question over here: Is it currently safe to use KeystoreCompat 1.1.2 and publish an app to the play store without it being rejected? Just wondering because you said you were working on a new version which didn't relay on `BIND_DEVICE_ADMIN`. We are working on an app that currently targets KitKat (pre-Lollipop) and I have this feeling `BIND_DEVICE_ADMIN` is sort of needed for such minSDK.

Thanks

**Comment by kotomisak** [comment]
Hey,

these are two things, you mentioned:

1) fulfill the Deceptive device policy. You must explain to users why you
are requesting the 'android.permission.BIND_DEVICE_ADMIN' in your app. Apps
must provide accurate disclosure of their functionality and should perform
as reasonably expected by the user. Any changes to device settings must be
made with the user's knowledge and consent and be easily reversible by the
user.

2) allow user to use KeystoreCompat library for some M or L and above. So
in case app supports Android L and above, you dont want to solve step 1)
above. Then it's good to modularize library and be able to use just parts
of the library. K+ or L+ or M+

Actually I am almost done with the second attempt of publishing the same
(with KitKat support) sample app again. I will try to fullfil step 1) above
- currently not 100% sure what all necessary steps I have to fulfill. Will
try it :-)

I would recommend for you to use KeystoreCompat 1.2.0

It's the version with shortened package.

https://bintray.com/kotomisak/cz.koto/android-keystore-compat/1.2.0

Happy coding!
Michal

**Comment by mradzinski** [comment]
```
Apps must provide accurate disclosure of their functionality and should perform
as reasonably expected by the user. Any changes to device settings must be
made with the user's knowledge and consent and be easily reversible by the
user.
```

One must learn to love how "clear" Google guidelines are sometimes :joy:. I'll try to find some more info regarding what they mean by `should perform as reasonably expected by the user` (that has many lectures) and I'll drop you a message here if I get to know a bit more.

Cheers!

**Comment by kotomisak** [comment]
This is complete mail I got last time, and then they really removed app from GooglePlay:

**Comment by kotomisak** [comment]
And few links to text above just for others:

**Comment by MjDevCz** [comment]
I fixed this issue the way to let user switch off DEVICE ADMIN RIGHT in the app directly (See sample app).
I also don't bind this code for lighter variant of library (elplus/emplus), thus programmers doesn't have to solve this issue.
