### ISSUE TITLE
Add minimal example code to readme

### ISSUE THREAD

**Issue by ssuukk** [kotomisak/security-showcase-android#33]
Hello,

Could you add minimal info on how to use it and minimal example code to the readme? I tried to crack one of your examples mentioned, but I really don't get those multiple dismiss settings, why are they and what for... Same goes with "force" settings...

**Comment by kotomisak** [comment]
Sure, will update it! Currently there is bit inconsistence between latest version in jcenter and code in reoository(thus readme). I will distribute the version 2.0 in to jcenter soon.

**Comment by javichaques** [comment]
Hello,

¿Where is the example?

Thank you

**Comment by devjta** [comment]
Yeah, referencing other projects is not a good "sample".. We want the code lines and not search for that in other projects.

Tough great work!

**Comment by MjDevCz** [comment]
Hah, Agree with that. I was really busy past few months and wasn't able to move samples forward. I hope I will have time and update samples in next month. Also I would like to update some topics here - according to new Android stuff.

**Comment by devjta** [comment]
And the other thing is, that the db-showcase-android uses an older version (cz.koto:android-keystore-compat:1.2.0) and therefore the example is utterly useless.
In 1.2.0 the KeystoreCompat was an "object" (I am not good in kotlin) and therefore KeystoreCompat.INSTANCE existed.. But with the current release, it is a normal class  and therefore there is no KeystoreCompat.INSTANCE..

Also your dependencies at the compat site are mostly "api", while in the example it is compile/implementation.

**Comment by MjDevCz** [comment]
Fixed here https://github.com/kotomisak/security-showcase-android/blob/develop/android-keystore-compat/readme.md

And now there is branch called `feature/version_3` which should bring better sample app for version 2.x of library and also for new version 3.x with androidX support.

**Comment by MjDevCz** [comment]
On comment for db-showcase, it is really outdated code and the only way to bring into play is rewrite it to maintainable and meaningful form. Which may be happen, but for now I just removed link to that repo and let's see.
