### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [kotomisak/security-showcase-android#34]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by kotomisak** [comment]
Hey, Oleksiy!

I will check your framework, since I have been using mockito with kotlin in more projects, than this.
I am just too busy now and have currently other issues as priority.
But thank you to reaching me out and I will definitely give you a feedback ;-)

**Comment by oleksiyp** [comment]
Merry Xmas :christmas_tree:  :christmas_tree:  :christmas_tree: :-)
